version: '3.8'
services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: decentrifi
      POSTGRES_PASSWORD: decentrifi
      POSTGRES_DB: decentrifi
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
