name: Build Go Modules

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


on:
  push:
    branches: [ "main" ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'services/data-aggregator/**'
      - '.github/workflows/build-go.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'services/data-aggregator/**'
      - '.github/workflows/build-go.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    
    - name: Build
      run: go build -v ./services/data-aggregator
    
    - name: Test
      run: go test -v ./services/data-aggregator

  docker:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/data-aggregator
        tags: |
          type=sha,format=short
          type=ref,event=branch
          latest
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: services/data-aggregator/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max